sudo: required
services:
  - docker
  
before_install:
  - docker build -t thiyaga/docker-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true thiyaga/docker-demo npm run test -- -- coverage  

deploy:
  provider: elasticbeanstalk
  region:  "us-east-1"
  app: "docker-demo"
  env: "DockerDemo-env"
  bucket_name: "elasticbeanstalk-us-east-1-097106885208"
  bucket_path: "docker-demo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  
  


